apiVersion: v1
kind: Service
metadata:
  name: hermes-data-api
  namespace: hermes
  labels:
    app.kubernetes.io/name: hermes-data-api
    app.kubernetes.io/part-of: hermes-data-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hermes-data-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
